
spring:
  application:
    name: testcontainers  
  jmx:
    enabled: false  
server:
  port: 17171
management:
  endpoint:
    env:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true  
  endpoints:
    web:
      exposure:
        include: ["health", "env", "info"]
      base-path: /
info:
  jdk-version: "${java.version} / ${java.vm.name}"
  host-operating-system: "${os.name} / ${os.version}"    